### ISSUE TITLE
il2cpp android support 

### ISSUE THREAD

**Issue by friuns2** [Misaka-Mikoto-Tech/MonoHook#11]
Hi great project, are you planning add android il2cpp support? 

There is android native hook library witch is using mprotect [https://github.com/iqiyi/xhook](https://github.com/iqiyi/xhook) maybe it could help

**Comment by friuns2** [comment]
fixed in #13

**Comment by Misaka-Mikoto-Tech** [comment]
has add support for android il2cpp armv7a and armv8a https://github.com/Misaka-Mikoto-Tech/MonoHook/commit/e9d97fcbd7fd1ebed6472d2566317dff149f4382 @friuns2

**Comment by friuns2** [comment]
thanks!
