### ISSUE TITLE
 proxy method bug

### ISSUE THREAD

**Issue by friuns2** [Misaka-Mikoto-Tech/MonoHook#14]
Hello there is bug with proxy method

this output should print 

TestPatch
Test
TestPatch
Test2

but it prints this
TestPatch
Test2
TestPatch
Test2

```csharp

using System;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.UI;

public class Test3 : MonoBehaviour
{
   public unsafe void Start()
   {
       Application.logMessageReceived+= ApplicationOnlogMessageReceived;

       Hook(Test, TestPatch, TestProxy);
       Hook(Test2, TestPatch, TestProxy);
       
       Test();
       Test2();

   }
   private void Hook(Action a, Action to, Action proxy)
   {
       var _hook = new MethodHook((a).Method, (to).Method, (proxy).Method);
       _hook.Install();
   }
   private static unsafe int* GetAddr(void* pointer)
   {
       return (int*) ((byte*)pointer + 1);
   }
   private void ApplicationOnlogMessageReceived(string condition, string stacktrace, LogType type)
   {
       text.text += condition + "\n";
   }
   [MethodImpl(MethodImplOptions.NoOptimization)]
   public void TestProxy()
   {
       Debug.Log("TestProxy");
   }
   
   
   [MethodImpl(MethodImplOptions.NoOptimization)]
   public void Test()
   {
       Debug.Log("Test");
   }
   
   [MethodImpl(MethodImplOptions.NoOptimization)]
   public void Test2()
   {
       Debug.Log("Test2");
   }
   
   
   public Text text;
   [MethodImpl(MethodImplOptions.NoOptimization)]
   public void TestPatch()
   {
       Debug.Log("TestPatch");
       TestProxy();
   }   
}

```

**Comment by Misaka-Mikoto-Tech** [comment]
> Hello there is bug with proxy method
> 
> this output should print
> 
> TestPatch Test TestPatch Test2
> 
> but it prints this TestPatch Test2 TestPatch Test2
> 
> ```cs
> using System;
> using System.Runtime.CompilerServices;
> using UnityEngine;
> using UnityEngine.UI;
> 
> public class Test3 : MonoBehaviour
> {
>    public unsafe void Start()
>    {
>        Application.logMessageReceived+= ApplicationOnlogMessageReceived;
> 
>        Hook(Test, TestPatch, TestProxy);
>        Hook(Test2, TestPatch, TestProxy);
>        
>        Test();
>        Test2();
> 
>    }
>    private void Hook(Action a, Action to, Action proxy)
>    {
>        var _hook = new MethodHook((a).Method, (to).Method, (proxy).Method);
>        _hook.Install();
>    }
>    private static unsafe int* GetAddr(void* pointer)
>    {
>        return (int*) ((byte*)pointer + 1);
>    }
>    private void ApplicationOnlogMessageReceived(string condition, string stacktrace, LogType type)
>    {
>        text.text += condition + "\n";
>    }
>    [MethodImpl(MethodImplOptions.NoOptimization)]
>    public void TestProxy()
>    {
>        Debug.Log("TestProxy");
>    }
>    
>    
>    [MethodImpl(MethodImplOptions.NoOptimization)]
>    public void Test()
>    {
>        Debug.Log("Test");
>    }
>    
>    [MethodImpl(MethodImplOptions.NoOptimization)]
>    public void Test2()
>    {
>        Debug.Log("Test2");
>    }
>    
>    
>    public Text text;
>    [MethodImpl(MethodImplOptions.NoOptimization)]
>    public void TestPatch()
>    {
>        Debug.Log("TestPatch");
>        TestProxy();
>    }   
> }
> ```

one proxy method should only be used for one hook instance, cause we will fill instructions jump to original method(the target method).

you can modify code like this below
```csharp
using System;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.UI;

public class Test3 : MonoBehaviour
{
    public unsafe void Start()
    {
        Application.logMessageReceived += ApplicationOnlogMessageReceived;

        Hook(Test, TestPatch, TestProxy);
        Hook(Test2, TestPatch2, TestProxy2);

        Test();
        Test2();

    }
    private void Hook(Action a, Action to, Action proxy)
    {
        var _hook = new MethodHook((a).Method, (to).Method, (proxy).Method);
        _hook.Install();
    }
    private static unsafe int* GetAddr(void* pointer)
    {
        return (int*)((byte*)pointer + 1);
    }
    private void ApplicationOnlogMessageReceived(string condition, string stacktrace, LogType type)
    {
        text.text += condition + "\n";
    }
    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestProxy()
    {
        Debug.Log("TestProxy");
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestProxy2()
    {
        Debug.Log("TestProxy2");
    }


    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void Test()
    {
        Debug.Log("Test");
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void Test2()
    {
        Debug.Log("Test2");
    }


    public Text text;
    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestPatch()
    {
        Debug.Log("TestPatch");
        TestProxy();
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestPatch2()
    {
        Debug.Log("TestPatch2");
        TestProxy2();
    }
}
```
@friuns2

**Comment by Misaka-Mikoto-Tech** [comment]
one proxy method should only be used for one hook instance, cause we will fill instructions jump to original method(the target method).

you can modify code like this below
```csharp
using System;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.UI;

public class Test3 : MonoBehaviour
{
    public unsafe void Start()
    {
        Application.logMessageReceived += ApplicationOnlogMessageReceived;

        Hook(Test, TestPatch, TestProxy);
        Hook(Test2, TestPatch2, TestProxy2);

        Test();
        Test2();

    }
    private void Hook(Action a, Action to, Action proxy)
    {
        var _hook = new MethodHook((a).Method, (to).Method, (proxy).Method);
        _hook.Install();
    }
    private static unsafe int* GetAddr(void* pointer)
    {
        return (int*)((byte*)pointer + 1);
    }
    private void ApplicationOnlogMessageReceived(string condition, string stacktrace, LogType type)
    {
        text.text += condition + "\n";
    }
    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestProxy()
    {
        Debug.Log("TestProxy");
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestProxy2()
    {
        Debug.Log("TestProxy2");
    }


    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void Test()
    {
        Debug.Log("Test");
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void Test2()
    {
        Debug.Log("Test2");
    }


    public Text text;
    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestPatch()
    {
        Debug.Log("TestPatch");
        TestProxy();
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    public void TestPatch2()
    {
        Debug.Log("TestPatch2");
        TestProxy2();
    }
}
```
@friuns2

**Comment by friuns2** [comment]
I don't have TestPatch2 or TestProxy2, im trying to integrate Lua so i have Only one void ExecuteLua(void* sourceMethodPtr) function

**Comment by Misaka-Mikoto-Tech** [comment]
you can write code like this
```csharp
void TestPatch()
    {
        var t = this.GetType();
        if(t == typeof(A))
        {
            // do something
            TestProxy();
        } else if(t == typeof(B))
        {
            // do something
            TestProxy2();
        }
    }
```

**Comment by friuns2** [comment]
yes but if i have a lot of functions in lua it gonna be complicated..

if could assign proxy method address in machine code something like this  
MOV proxymethod, address  
JMP overridemethod

**Comment by friuns2** [comment]
this is what I'm trying to achieve, i need transfer originalMethodName 

[https://github.com/friuns2/MonoHook/blob/adca0cb6e8ea2db20e150f9b4e28b4e9d3d00362/Assets/Test4.cs#L47](https://github.com/friuns2/MonoHook/blob/adca0cb6e8ea2db20e150f9b4e28b4e9d3d00362/Assets/Test4.cs#L47)

if you have any ideas how to do this :)

**Comment by Misaka-Mikoto-Tech** [comment]
you can write a Common Monobeviour script for all lua ui, when you want to create a ui at lua, you can add the script 
 `uigo.AddComponent<LuaViewRunner>()`， and set lua table to its field, 

script file may like this
```csharp

LuaTable _luatable;
void Update()
{
    _luatable.GetFunction("Update")();
}

void LateUpdate()
{
    _luatable.GetFunction("LateUpdate")();
}
```

https://github.com/Misaka-Mikoto-Tech/UIControlBinding/blob/master/Assets/UIControlBinding/Scripts/LuaViewRunner.cs

**Comment by friuns2** [comment]
yes that what I'm trying to do, but i want override any method with monohook

**Comment by friuns2** [comment]
rbp register write to static variable before JMP would be useful in this case :)

**Comment by friuns2** [comment]
Here is what I'm working on https://github.com/friuns2/LuaMod

**Comment by friuns2** [comment]
can you help with unrelated question, why this code not outputs 34?
```csharp
 public static unsafe void Main(string[] args)
    {
        Action<int> act = Test3;
        Action<float> action = Unsafe.Read<Action<float>>(Unsafe.AsPointer(ref act)); // cast 
        action(34);

    }
    
    private static unsafe void Test3( int c) 
    {
        var g = (bool*)&c;
        Console.WriteLine(*g);
    }

```

**Comment by Misaka-Mikoto-Tech** [comment]
> 

Because `Action<float>` uses `xmm0` to pass the first parameter, but `Action<int>` receives the first parameter through `ecx` , so the parameter `int c` will be a random value.
