### ISSUE TITLE
Hook doesn't work On GenericMethod

### ISSUE THREAD

**Issue by zsy2015** [Misaka-Mikoto-Tech/MonoHook#15]
for example :  UnityEngine.Object  Api:  public static T Instantiate<T>(T original) where T : Object;
when i  Get the this GenericMethod, and then us 
"MethodInfo miTarget = genericMethod.MakeGenericMethod(typeof(UnityEngine.Object)",

and then Code:

    [MethodImpl(MethodImplOptions.NoOptimization)]
    private static UnityEngine.Object GameInstanceNew(UnityEngine.Object go)
    {
        Debug.LogFormat("【自定义实现】Object.Instantiate(Object original), Prefab名称：{0}", go.name);
        UnityEngine.Object  obj= GameInstanceProxy(go);
        return obj;
    }
    [MethodImpl(MethodImplOptions.NoOptimization)]
    private static UnityEngine.Object GameInstanceProxy(UnityEngine.Object go)
    {
        // 此处的函数实现永远不会起作用，随便写
        Debug.Log("something" + go.ToString());
        return null;
    }
    MethodInfo miReplacement = new Func<UnityEngine.Object, UnityEngine.Object>(GameInstanceNew).Method;
    MethodInfo miProxy = new Func<UnityEngine.Object, UnityEngine.Object>(GameInstanceProxy).Method;
    _hook_Instance = new MethodHook(miTarget, miReplacement, miProxy);
    _hook_Instance.Install();

And when Call UnityEngine.Object:Instance() Again ,  then  Unity  crash~!

Code no Error in Runtime, but hook doesn.t work,    who know reason

**Comment by Misaka-Mikoto-Tech** [comment]
3a77f0b39895b19ccdb227339d00b869e493c90d
已添加泛型hook测试用例，但目前仅支持 il2cpp, 一般情况泛型函数都会去调用一个非泛型方法，建议去hook对应的非泛型方法
