### ISSUE TITLE
MonoHook makes Unity2021.3.6 crash

### ISSUE THREAD

**Issue by hanxu1210** [Misaka-Mikoto-Tech/MonoHook#17]
Upgraded my project from Unity2019 to 2021.3.6 recently, and MonoHook started making Unity crash when it calls the Monohook funcs(start unity; press Play Button in editor; modified script). It's not 100% crash, but once my computer randomly met this crash, i can repeat the crash by pressing Play Button until i removed the "new MethodHook()" invoking functions. And this type of crash can be repeated on other computers.
自从最近升级到2021.3.6后，开始遇到MonoHook的crash问题。只要是调用到了绑定hook的代码，无论是在启动unity、点击编辑器的play，修改了script，都会随机的遇到unity native crash。已经定位确实是monohook的绑定代码造成的（只要不调用，就必然不会crash）。在好几台电脑上都可以重现。保持projectSetting里ReloadDomon默认开启的状态下，通过点击play可以比较快速的，重现率高的，重现这个问题。
麻烦调查一下，否则就不能再用MonoHook了:(

crash info:
Obtained 2 stack frames
RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
<Missing stacktrace information>

test env: scripting backend: mono. ApiCompatibilityLevel: .both .net framework or .net standard

would you please have a  look at this issue? thanks a lot!

**Comment by Misaka-Mikoto-Tech** [comment]
周末看一下

**Comment by hanxu1210** [comment]
多谢大佬

**Comment by Misaka-Mikoto-Tech** [comment]
d81f9ca052248bb10c29106fc6ec8ba9eb0b4cb6
已修复

**Comment by hanxu1210** [comment]
还是会crash（在点play后）。之前报问题有提到，这个crash不仅是play时会遇到，在启动unity时也会遇到，所以，感觉这样改可能不是问题的本源。
其次，现在这样改了，退出play后会uninstall，那么接下来在编辑器模式中，是处于没有hook的状态。这在功能上和之前也产生了变化：之前的hook发生在reload时（靠[DidReloadScripts]），所以，编辑中、play中，都是hook的状态（我的项目在主要是在编辑模式下，hook了函数，来强化编辑器功能）。
因为这个crash比较随机，经常改了点啥，一阵子就又遇不到crash了，或者改了点啥，一阵子就每次都crash。我把你新加的ExitingPlayMode改成ExitingEditMode，好像这阵子又没crash。。

**Comment by Misaka-Mikoto-Tech** [comment]
> 还是会crash（在点play后）。之前报问题有提到，这个crash不仅是play时会遇到，在启动unity时也会遇到，所以，感觉这样改可能不是问题的本源。 其次，现在这样改了，退出play后会uninstall，那么接下来在编辑器模式中，是处于没有hook的状态。这在功能上和之前也产生了变化：之前的hook发生在reload时（靠[DidReloadScripts]），所以，编辑中、play中，都是hook的状态（我的项目在主要是在编辑模式下，hook了函数，来强化编辑器功能）。 因为这个crash比较随机，经常改了点啥，一阵子就又遇不到crash了，或者改了点啥，一阵子就每次都crash。我把你新加的ExitingPlayMode改成ExitingEditMode，好像这阵子又没crash。。

问题的根源应该就是新版Unity的Reload模式发生了变化，所以需要想办法避免二次hook，彻底的解决方案是修改判断是否已经Hook的方法，改成判断需要覆盖的二进制是否跟现有的相同，相同就说明已经hook了

**Comment by snaketears** [comment]
> [d81f9ca](https://github.com/Misaka-Mikoto-Tech/MonoHook/commit/d81f9ca052248bb10c29106fc6ec8ba9eb0b4cb6) 已修复

刚才重新试了下，还是会crash。

**Comment by Misaka-Mikoto-Tech** [comment]
已发现原因，是x64的跳转地址特殊情况下计算错误，正在尝试修复

**Comment by Misaka-Mikoto-Tech** [comment]
> 还是会crash（在点play后）。之前报问题有提到，这个crash不仅是play时会遇到，在启动unity时也会遇到，所以，感觉这样改可能不是问题的本源。 其次，现在这样改了，退出play后会uninstall，那么接下来在编辑器模式中，是处于没有hook的状态。这在功能上和之前也产生了变化：之前的hook发生在reload时（靠[DidReloadScripts]），所以，编辑中、play中，都是hook的状态（我的项目在主要是在编辑模式下，hook了函数，来强化编辑器功能）。 因为这个crash比较随机，经常改了点啥，一阵子就又遇不到crash了，或者改了点啥，一阵子就每次都crash。我把你新加的ExitingPlayMode改成ExitingEditMode，好像这阵子又没crash。。

d0fd8d86b1d710de6089c026c3c3c6035d9a4d70 已修复，可以再测试一下

**Comment by Misaka-Mikoto-Tech** [comment]
> > [d81f9ca](https://github.com/Misaka-Mikoto-Tech/MonoHook/commit/d81f9ca052248bb10c29106fc6ec8ba9eb0b4cb6) 已修复
> 
> 刚才重新试了下，还是会crash。

d0fd8d86b1d710de6089c026c3c3c6035d9a4d70 已修复，可以再测试一下

**Comment by hanxu1210** [comment]
> > 还是会crash（在点play后）。之前报问题有提到，这个crash不仅是play时会遇到，在启动unity时也会遇到，所以，感觉这样改可能不是问题的本源。 其次，现在这样改了，退出play后会uninstall，那么接下来在编辑器模式中，是处于没有hook的状态。这在功能上和之前也产生了变化：之前的hook发生在reload时（靠[DidReloadScripts]），所以，编辑中、play中，都是hook的状态（我的项目在主要是在编辑模式下，hook了函数，来强化编辑器功能）。 因为这个crash比较随机，经常改了点啥，一阵子就又遇不到crash了，或者改了点啥，一阵子就每次都crash。我把你新加的ExitingPlayMode改成ExitingEditMode，好像这阵子又没crash。。
> 
> [d0fd8d8](https://github.com/Misaka-Mikoto-Tech/MonoHook/commit/d0fd8d86b1d710de6089c026c3c3c6035d9a4d70) 已修复，可以再测试一下

试了一会，没有遇到crash了
