### ISSUE TITLE
2019.4.40编辑器下gameobject.setactive不好用

### ISSUE THREAD

**Issue by sophiepeithos** [Misaka-Mikoto-Tech/MonoHook#18]
![image](https://user-images.githubusercontent.com/1758796/195759226-76ce674e-319d-40e1-a94f-80233f1d398a.png)
调用MonoHook.Test.GameObject_SetActive_HookTest.Test(gameObject)好用
调用gameObject.SetActive(false)不好用
GameObject_SetActive_HookTest已经使用了InitializeOnLoad

是我工程设置或者脚本写错了吗

**Comment by Misaka-Mikoto-Tech** [comment]
给个测试用例

**Comment by sophiepeithos** [comment]
> 

我的截图里就是测试用例

**Comment by Misaka-Mikoto-Tech** [comment]
没有测试用例，先关闭
