### ISSUE TITLE
使用注入Hook的方式运行时，无法正确运行原函数

### ISSUE THREAD

**Issue by pgw00k** [Misaka-Mikoto-Tech/MonoHook#7]
我fork了一份进行了修改，配合注入工具能够成功注入到运行时的 Unity 程序中，大部分功能也都正常，但是有几个问题，不知道大佬能不能给点思路（对汇编不是很熟悉）：
1. 能够Hook到指定的函数，也确实能够跳转到新函数，但是调用占位原函数时失效，没有效果
2. Hook带有参数的方法时无效，Hook不到具体的参数

大概的逻辑在这里：[https://github.com/pgw00k/MonoHook](https://github.com/pgw00k/MonoHook)

**Comment by Misaka-Mikoto-Tech** [comment]
我试了下，dll 没有被加载，所以我不太清楚如何才能加载

**Comment by pgw00k** [comment]
主要是想通过这种方式了解一下CLR HOOK的原理，我是通过另外的注入工具注入到进程中运行的，或者大大能给个示例之类的吗？

**Comment by Misaka-Mikoto-Tech** [comment]
> 主要是想通过这种方式了解一下CLR HOOK的原理，我是通过另外的注入工具注入到进程中运行的，或者大大能给个示例之类的吗？

这不是CLR hook，这是 native hook，原理就是无论是jit还是aot模式执行的C#方法，在第一次调用前一定已经是native代码了，所以只要想办法找到这个native代码的内存地址就可以按native hook的方式进行hook了
